update zhangge‘s cckiller

diff --git a/jst_server_shell/cckiller/etc/init.d/cckiller b/jst_server_shell/cckiller/etc/init.d/cckiller
--- a/jst_server_shell/cckiller/etc/init.d/cckiller
+++ b/jst_server_shell/cckiller/etc/init.d/cckiller
@@ -2,28 +2,28 @@
 EXEC_PATH=/usr/local/cckiller
 EXEC=cckiller
 DAEMON=$EXEC_PATH/$EXEC
-PID_FILE=/var/run/$EXEC.pid  
+PID_FILE=/var/run/$EXEC.pid
 
 test -f /etc/rc.d/init.d/functions && . /etc/rc.d/init.d/functions
 
-if [ ! -f $DAEMON ] ; then  
-       echo "ERROR: $DAEMON not found"  
-       exit 1  
+if [ ! -f $DAEMON ] ; then
+       echo "ERROR: $DAEMON not found"
+       exit 1
 else
         chmod +x $DAEMON
 fi
 
-stop()  
-{  
-       echo -n "Shutting down $EXEC ..."  
-       ps aux | grep "$DAEMON" | grep -v grep | kill -9 `awk '{print $2}'` >/dev/null 2>&1  
+stop()
+{
+       echo -n "Shutting down $EXEC ..."
+       ps aux | grep "$DAEMON" | grep -v grep | kill -9 `awk '{print $2}'` >/dev/null 2>&1
        rm -f $PID_FILE
-       usleep 100  
-       echo -e "                 [ \033[36mOK\033[0m ]"   
+       usleep 100
+       echo -e "                 [ \033[36mOK\033[0m ]"
 }
 
-start()  
-{  
+start()
+{
 
 	if [[ -f  $PID_FILE ]]
 	then
@@ -31,8 +31,8 @@ start()
         	exit 1
 	fi
 
-    echo -n "Starting $EXEC ..."  
-    $DAEMON --process > /dev/null &  
+    echo -n "Starting $EXEC ..."
+    $DAEMON --process > /dev/null &
     #pidof $EXEC > $PID_FILE
     PID=$(ps aux | grep "$DAEMON" | grep -v grep | awk '{print $2}')
     if [[ ! -z $PID ]]
@@ -45,30 +45,30 @@ start()
 	fi
 }
 
-restart()  
-{  
+restart()
+{
     stop
     echo
     start
-}  
+}
 echo
-case "$1" in  
+case "$1" in
     start)
         start
-        ;;  
-    stop)  
-        stop  
-        ;;  
-    restart)  
-        restart  
-        ;;  
-    status)  
+        ;;
+    stop)
+        stop
+        ;;
+    restart)
+        restart
+        ;;
+    status)
         $DAEMON --show
         status -p $PID_FILE $DAEMON
-        ;; 
-    *)  
-        echo "Usage: service $EXEC {start|stop|restart|status}"  
-        exit 1  
+        ;;
+    *)
+        echo "Usage: service $EXEC {start|stop|restart|status}"
+        exit 1
 esac
 echo
 exit $?
